version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resume-website"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xklnde3x8tc3"
s3_prefix = "resume-website"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
